// <auto-generated />
using System;
using IdentityService.Data.DatabaseContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdentityService.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240527135424_Changed_Nullability")]
    partial class Changed_Nullability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.Audit.AuditTrail", b =>
                {
                    b.Property<long>("AuditTrailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actions")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewData")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldData")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TableIdValue")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TableIdValueGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("AuditTrailId");

                    b.ToTable("DbAuditTrail", "Audit");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.CountryCodebook", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ActiveFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("ActiveFrom")
                        .HasColumnOrder(991);

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ActiveTo")
                        .HasColumnOrder(992);

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateCreated")
                        .HasColumnOrder(1005);

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateDeleted")
                        .HasColumnOrder(1020);

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateModified")
                        .HasColumnOrder(1010);

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("Deleted")
                        .HasColumnOrder(996);

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description")
                        .HasColumnOrder(2);

                    b.Property<string>("ISO_3166_ALPHA_2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT")
                        .HasColumnName("ISO_3166_ALPHA_2");

                    b.Property<string>("ISO_3166_ALPHA_3")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("ISO_3166_ALPHA_3");

                    b.Property<string>("ISO_3166_NUMERIC")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT")
                        .HasColumnName("ISO_3166_NUMERIC");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive")
                        .HasColumnOrder(990);

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalName")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT")
                        .HasColumnName("HR_NAME");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT")
                        .HasColumnName("INT_NAME");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.ToTable("Countries", "Codebook");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.Inbox.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InboxMessages", (string)null);
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.OutboxPattern.InternalCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EnqueueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InternalCommands", (string)null);
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.OutboxPattern.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedByApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ActiveFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("ActiveFrom")
                        .HasColumnOrder(991);

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ActiveTo")
                        .HasColumnOrder(992);

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateCreated")
                        .HasColumnOrder(1005);

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateDeleted")
                        .HasColumnOrder(1020);

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateModified")
                        .HasColumnOrder(1010);

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("Deleted")
                        .HasColumnOrder(996);

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedByApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive")
                        .HasColumnOrder(990);

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModifiedByApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.Resource", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedByApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ActiveFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("ActiveFrom")
                        .HasColumnOrder(991);

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ActiveTo")
                        .HasColumnOrder(992);

                    b.Property<string>("ControllerActionName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ControllerName")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedByApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateCreated")
                        .HasColumnOrder(1005);

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateDeleted")
                        .HasColumnOrder(1020);

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateModified")
                        .HasColumnOrder(1010);

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("Deleted")
                        .HasColumnOrder(996);

                    b.Property<Guid?>("DeletedByApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive")
                        .HasColumnOrder(990);

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModifiedByApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportName")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResourceType")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedByApplicationUserId");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("DeletedByApplicationUserId");

                    b.HasIndex("ModifiedByApplicationUserId");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.RolePermission", b =>
                {
                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PermissionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ResourceId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("ActiveFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("ActiveFrom")
                        .HasColumnOrder(991);

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ActiveTo")
                        .HasColumnOrder(992);

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateCreated")
                        .HasColumnOrder(1005);

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateDeleted")
                        .HasColumnOrder(1020);

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateModified")
                        .HasColumnOrder(1010);

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("Deleted")
                        .HasColumnOrder(996);

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description")
                        .HasColumnOrder(2);

                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive")
                        .HasColumnOrder(990);

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Name")
                        .HasColumnOrder(1);

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("BLOB");

                    b.Property<bool>("TestData")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "PermissionId", "ResourceId");

                    b.HasIndex("DeletedById");

                    b.HasIndex("PermissionId");

                    b.HasIndex("ResourceId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.Tenant", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ActiveFrom")
                        .HasColumnType("TEXT")
                        .HasColumnName("ActiveFrom")
                        .HasColumnOrder(991);

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ActiveTo")
                        .HasColumnOrder(992);

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateCreated")
                        .HasColumnOrder(1005);

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateDeleted")
                        .HasColumnOrder(1020);

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT")
                        .HasColumnName("DateModified")
                        .HasColumnOrder(1010);

                    b.Property<bool>("Deleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("Deleted")
                        .HasColumnOrder(996);

                    b.Property<Guid>("DeletedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("Description")
                        .HasColumnOrder(2);

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("IsActive")
                        .HasColumnOrder(990);

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("TEXT")
                        .HasColumnName("TenantName");

                    b.Property<byte[]>("RowVersion")
                        .HasColumnType("BLOB");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.ToTable("Tenants", "Codebook");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.AccountJournal.AccountJournalEntry", b =>
                {
                    b.Property<Guid>("JournalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ActingEmail")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActingUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActingUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2024, 5, 27, 13, 54, 24, 757, DateTimeKind.Unspecified).AddTicks(7559), new TimeSpan(0, 0, 0, 0, 0)));

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailActedUpon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Seen")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserActedUponId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserNameActedUpon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JournalId");

                    b.HasIndex("UserId");

                    b.ToTable("AccountJournalEntry");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.AddressSubAggregate.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AddressIdGuid")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlatNr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HouseNumberSuffix")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Line2")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserComment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("_addressTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AddressTypeId                                   ");

                    b.Property<int?>("_cityBlockId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CityBlockId");

                    b.Property<int?>("_countryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CountryId");

                    b.Property<int?>("_countyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CountyId");

                    b.Property<int?>("_townId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TownId");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("UndeletedById");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.AddressSubAggregate.AddressType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("UndeletedById");

                    b.ToTable("AddressTypes");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.AddressSubAggregate.UserAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<long>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserRoleGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("UndeletedById");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddress");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.RefreshTokenEntity.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.RoleSubAggregate.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleIdGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("UndeletedById");

                    b.ToTable("ApplicationRoles");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.RoleSubAggregate.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserRoleGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("RoleId");

                    b.HasIndex("UndeletedById");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("LastVerificationFailureDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestVerificationFailureMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Oib")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PasswordReset")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ResetTokenExpires")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("VerificationTokenExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Verified")
                        .HasColumnType("TEXT");

                    b.Property<byte>("_status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StatusId");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("Email");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("Oib")
                        .IsUnique();

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("UndeletedById");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.CountryCodebook", b =>
                {
                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById");

                    b.Navigation("ActivatedBy");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.Resource", b =>
                {
                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedByApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ActivatedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.RolePermission", b =>
                {
                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IdentityService.Domain.DomainEntities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdentityService.Domain.DomainEntities.Resource", "Resource")
                        .WithMany("RolePermissions")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.RoleSubAggregate.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeletedBy");

                    b.Navigation("Permission");

                    b.Navigation("Resource");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.Tenant", b =>
                {
                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById");

                    b.Navigation("ActivatedBy");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.AccountJournal.AccountJournalEntry", b =>
                {
                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", null)
                        .WithMany("JournalEntries")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.AddressSubAggregate.Address", b =>
                {
                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivatedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("UndeletedBy");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.AddressSubAggregate.AddressType", b =>
                {
                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivatedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("UndeletedBy");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.AddressSubAggregate.UserAddress", b =>
                {
                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.AddressSubAggregate.Address", "Address")
                        .WithMany("UserAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("ActivatedBy");

                    b.Navigation("Address");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("UndeletedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.RefreshTokenEntity.RefreshToken", b =>
                {
                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ApplicationUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.RoleSubAggregate.Role", b =>
                {
                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivatedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("UndeletedBy");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.RoleSubAggregate.UserRole", b =>
                {
                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.RoleSubAggregate.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("ActivatedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("Role");

                    b.Navigation("UndeletedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.User", b =>
                {
                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdentityService.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivatedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("UndeletedBy");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.Resource", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.AddressSubAggregate.Address", b =>
                {
                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.RoleSubAggregate.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("IdentityService.Domain.DomainEntities.UserAggregate.User", b =>
                {
                    b.Navigation("JournalEntries");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserAddresses");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
