// <auto-generated />
using System;
using EventDriven.Domain.PoC.Repository.EF.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EventDriven.Domain.PoC.Repository.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210812154330_some-stuff")]
    partial class somestuff
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.Audit.AuditTrail", b =>
                {
                    b.Property<long>("AuditTrailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Actions")
                        .HasColumnType("TEXT");

                    b.Property<string>("NewData")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldData")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TableIdValue")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TableIdValueGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("TableName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("AuditTrailId");

                    b.ToTable("DbAuditTrail", "Audit");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.OutboxPattern.InternalCommand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EnqueueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InternalCommands");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.OutboxPattern.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AccountJournal.AccountJournalEntry", b =>
                {
                    b.Property<Guid>("JournalId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActingEmail")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActingUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ActingUserName")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(new DateTimeOffset(new DateTime(2021, 8, 12, 15, 43, 29, 901, DateTimeKind.Unspecified).AddTicks(224), new TimeSpan(0, 0, 0, 0, 0)));

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailActedUpon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("Seen")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserActedUponId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserNameActedUpon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("JournalId");

                    b.HasIndex("ActingUserId");

                    b.ToTable("AccountJournalEntry");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.Address", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AddressIdGuid")
                        .HasColumnType("TEXT");

                    b.Property<long>("AddressTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("CityBlockId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CityBlockId1");

                    b.Property<long?>("CountryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CountryId1");

                    b.Property<long?>("CountyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CountyId1");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FlatNr")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HouseNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HouseNumberSuffix")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Line1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Line2")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PostalCode")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<long?>("TownId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TownId1");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserComment")
                        .HasColumnType("TEXT");

                    b.Property<int?>("_addressTypeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("AddressTypeId                                   ");

                    b.Property<int?>("_cityBlockId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CityBlockId");

                    b.Property<int?>("_countryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CountryId");

                    b.Property<int?>("_countyId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CountyId");

                    b.Property<int?>("_townId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TownId");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("CityBlockId");

                    b.HasIndex("CountryId");

                    b.HasIndex("CountyId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("TownId");

                    b.HasIndex("UndeletedById");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.AddressType", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("UndeletedById");

                    b.ToTable("AddressTypes");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.CityBlock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("UndeletedById");

                    b.ToTable("CityBlock");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("UndeletedById");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.County", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("UndeletedById");

                    b.ToTable("County");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.Town", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZipCode")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("UndeletedById");

                    b.ToTable("Town");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.UserAddress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<long>("AddressId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserRoleGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("UndeletedById");

                    b.HasIndex("UserId");

                    b.ToTable("UserAddress");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.RefreshToken.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LastModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("TEXT");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("LastModifiedById");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.RoleSubAggregate.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleIdGuid")
                        .HasColumnType("TEXT");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("UndeletedById");

                    b.ToTable("ApplicationRoles");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.RoleSubAggregate.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<long>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserRoleGuid")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("RoleId");

                    b.HasIndex("UndeletedById");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActivatedById")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ActiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ActiveTo")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeactivateReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailVerificationToken")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSeed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastVerificationFailureDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LatestVerificationFailureMessage")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ModifiedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Oib")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordReset")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetMsg")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReactivatedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReactivatedReason")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResetToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UndeleteReason")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UndeletedById")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerificationTokenExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Verified")
                        .HasColumnType("TEXT");

                    b.Property<byte>("_status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StatusId");

                    b.HasKey("Id");

                    b.HasIndex("ActivatedById");

                    b.HasIndex("CreatedById");

                    b.HasIndex("DeactivatedById");

                    b.HasIndex("DeletedById");

                    b.HasIndex("Email");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("Oib")
                        .IsUnique();

                    b.HasIndex("ReactivatedById");

                    b.HasIndex("UndeletedById");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AccountJournal.AccountJournalEntry", b =>
                {
                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ActingUser")
                        .WithMany()
                        .HasForeignKey("ActingUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "UserActedUpon")
                        .WithMany("JournalEntries")
                        .HasForeignKey("JournalId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("ActingUser");

                    b.Navigation("UserActedUpon");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.Address", b =>
                {
                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.CityBlock", "CityBlock")
                        .WithMany()
                        .HasForeignKey("CityBlockId");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.County", "County")
                        .WithMany()
                        .HasForeignKey("CountyId");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.Town", "Town")
                        .WithMany()
                        .HasForeignKey("TownId");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivatedBy");

                    b.Navigation("CityBlock");

                    b.Navigation("Country");

                    b.Navigation("County");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("Town");

                    b.Navigation("UndeletedBy");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.AddressType", b =>
                {
                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivatedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("UndeletedBy");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.CityBlock", b =>
                {
                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById");

                    b.Navigation("ActivatedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("UndeletedBy");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.Country", b =>
                {
                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById");

                    b.Navigation("ActivatedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("UndeletedBy");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.County", b =>
                {
                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById");

                    b.Navigation("ActivatedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("UndeletedBy");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.Town", b =>
                {
                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById");

                    b.Navigation("ActivatedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("UndeletedBy");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.UserAddress", b =>
                {
                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.Address", "Address")
                        .WithMany("UserAddresses")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "User")
                        .WithMany("UserAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("ActivatedBy");

                    b.Navigation("Address");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("UndeletedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.RefreshToken.RefreshToken", b =>
                {
                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ApplicationUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "LastModifiedBy")
                        .WithMany()
                        .HasForeignKey("LastModifiedById");

                    b.Navigation("ApplicationUser");

                    b.Navigation("LastModifiedBy");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.RoleSubAggregate.Role", b =>
                {
                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivatedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("UndeletedBy");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.RoleSubAggregate.UserRole", b =>
                {
                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.RoleSubAggregate.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("ActivatedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("Role");

                    b.Navigation("UndeletedBy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", b =>
                {
                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ActivatedBy")
                        .WithMany()
                        .HasForeignKey("ActivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeactivatedBy")
                        .WithMany()
                        .HasForeignKey("DeactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "DeletedBy")
                        .WithMany()
                        .HasForeignKey("DeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ModifiedBy")
                        .WithMany()
                        .HasForeignKey("ModifiedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "ReactivatedBy")
                        .WithMany()
                        .HasForeignKey("ReactivatedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", "UndeletedBy")
                        .WithMany()
                        .HasForeignKey("UndeletedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ActivatedBy");

                    b.Navigation("CreatedBy");

                    b.Navigation("DeactivatedBy");

                    b.Navigation("DeletedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("ReactivatedBy");

                    b.Navigation("UndeletedBy");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.AddressSubAggregate.Address", b =>
                {
                    b.Navigation("UserAddresses");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.RoleSubAggregate.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EventDriven.Domain.PoC.Domain.DomainEntities.UserAggregate.User", b =>
                {
                    b.Navigation("JournalEntries");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserAddresses");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
